kind: BuildConfig
apiVersion: v1
metadata:
  name: ophicleide-training
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ophicleide/ophicleide-training
      ref: develop
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: ophicleide-training:latest