apiVersion: v1
kind: Route
metadata:
  labels:
    app: jgrafzahl
    application: oshinko-java-spark
    createdBy: template-oshinko-java-build-dc
  name: jgrafzahl
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: jgrafzahl
    weight: 100
  wildcardPolicy: None