apiVersion: v1
kind: BuildConfig
metadata:
  name: word-fountain
  selfLink: /oapi/v1/namespaces/ophicleide/buildconfigs/word-fountain
  labels:
    app: word-fountain
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/mattf/word-fountain
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python-27-centos7:latest
  output:
    to:
      kind: ImageStreamTag
      name: word-fountain:latest
  triggers:
    - github:
        secret: dhKvNUAm147uDrWB0VPP
      type: GitHub
    - generic:
        secret: i3rDbetKaW0F35w-_WSu
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: >-
          openshift/python-27-centos7@sha256:dc5e884c8f5f0a836f06fc8104131c4a013a9ea9dbac002d4121fdd5e353fe03
      type: ImageChange