apiVersion: v1
kind: DeploymentConfig
metadata:
  name: word-fountain
  labels:
    app: word-fountain
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - word-fountain
        from:
          kind: ImageStreamTag
          namespace: radtests
          name: 'word-fountain:latest'
  replicas: 1
  test: false
  selector:
    app: word-fountain
    deploymentconfig: word-fountain
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: word-fountain
        deploymentconfig: word-fountain
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: word-fountain
          image: 'word-fountain:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SERVERS
              value: 'apache-kafka:9092'
          resources: {}
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
