apiVersion: v1
kind: ImageStream
metadata:
  generation: 2
  labels:
    app: word-fountain
  name: python-27-centos7
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/imported-from: openshift/python-27-centos7
      from:
        kind: DockerImage
        name: openshift/python-27-centos7
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
