apiVersion: v1
kind: Service
metadata:
  name: word-fountain
  selfLink: /api/v1/namespaces/ophicleide/services/word-fountain
  labels:
    app: word-fountain
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: word-fountain
    deploymentconfig: word-fountain

