apiVersion: v1
kind: Route
metadata:
  labels:
    app: grafzahl
    application: oshinko-pyspark
  name: grafzahl
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: grafzahl
  wildcardPolicy: None